/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    footer: Footer;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  /**
   * Заголовок статті
   */
  title: string;
  /**
   * URL-адреса статті (наприклад: my-article)
   */
  slug: string;
  /**
   * Автор статті
   */
  author: string | User;
  /**
   * Дата публікації
   */
  publishedAt?: string | null;
  /**
   * Статус статті
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Головне зображення статті
   */
  featuredImage?: (string | null) | Media;
  /**
   * Короткий опис статті (для превью)
   */
  excerpt?: string | null;
  /**
   * Основний контент статті
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Категорії статті
   */
  categories?: (string | BlogCategory)[] | null;
  /**
   * Теги для статті
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO заголовок (якщо відрізняється від основного)
   */
  metaTitle?: string | null;
  /**
   * SEO опис
   */
  metaDescription?: string | null;
  /**
   * Час читання в хвилинах (заповнюється автоматично або вручну)
   */
  readTime?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: string;
  /**
   * Назва категорії
   */
  name: string;
  /**
   * URL-адреса категорії
   */
  slug: string;
  /**
   * Опис категорії
   */
  description?: string | null;
  /**
   * Колір категорії (hex код, наприклад: #ff0000)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishedAt?: T;
  status?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  readTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Налаштування домашньої сторінки та її секцій
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  /**
   * Заголовок сторінки
   */
  title: string;
  /**
   * Мета-опис для SEO
   */
  metaDescription?: string | null;
  /**
   * Налаштування головної секції
   */
  heroSection: {
    /**
     * Заголовок hero секції
     */
    title: string;
    /**
     * Підзаголовок hero секції
     */
    subtitle?: string | null;
    /**
     * Текст першої кнопки
     */
    buttonText?: string | null;
    /**
     * Посилання першої кнопки
     */
    buttonLink?: string | null;
    /**
     * Текст другої кнопки
     */
    button2Text?: string | null;
    /**
     * Посилання другої кнопки
     */
    button2Link?: string | null;
  };
  /**
   * Налаштування секції 'Про нас'
   */
  aboutSection: {
    /**
     * Заголовок секції 'Про нас'
     */
    title: string;
    /**
     * Додайте до 4 карточок для секції 'Про нас'
     */
    aboutCards?:
      | {
          /**
           * Текст карточки
           */
          text: string;
          /**
           * Зображення для карточки
           */
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Налаштування секції 'Послуги'
   */
  servicesSection: {
    /**
     * Заголовок секції 'Послуги'
     */
    title: string;
    /**
     * Число для відображення (наприклад, '4')
     */
    number?: string | null;
    /**
     * Додайте до 4 карточок для секції 'Послуги'
     */
    serviceCards?:
      | {
          /**
           * Варіант кольору карточки
           */
          variant: 'green' | 'yellow' | 'orange' | 'blue';
          /**
           * Назва табору (наприклад, 'Next Camp')
           */
          title: string;
          /**
           * Підзаголовок (наприклад, 'Весна')
           */
          subtitle?: string | null;
          /**
           * Додайте пункти списку для карточки
           */
          content?:
            | {
                /**
                 * Текст пункту списку
                 */
                item: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Текст першої кнопки
           */
          firstButtonText?: string | null;
          /**
           * Посилання першої кнопки
           */
          firstButtonLink?: string | null;
          /**
           * Текст другої кнопки
           */
          secondButtonText?: string | null;
          /**
           * Посилання другої кнопки
           */
          secondButtonLink?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Додайте інші секції для домашньої сторінки
   */
  sections?:
    | {
        /**
         * Виберіть тип секції
         */
        sectionType: 'gallery' | 'testimonials' | 'contacts' | 'custom';
        /**
         * Заголовок секції
         */
        title: string;
        /**
         * Підзаголовок секції
         */
        subtitle?: string | null;
        /**
         * Додайте зображення для галереї
         */
        images?:
          | {
              image: string | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Додайте відгуки
         */
        testimonials?:
          | {
              author: string;
              text: string;
              rating?: number | null;
              avatar?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Налаштування футера та контактної інформації
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  contactInfo?: {
    /**
     * Номер телефону для контактів
     */
    phone?: string | null;
    /**
     * Email адреса
     */
    email?: string | null;
    /**
     * Telegram username або посилання (наприклад: @username або https://t.me/username)
     */
    telegram?: string | null;
    /**
     * Instagram username або посилання (наприклад: @username або https://instagram.com/username)
     */
    instagram?: string | null;
  };
  additionalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  title?: T;
  metaDescription?: T;
  heroSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonText?: T;
        buttonLink?: T;
        button2Text?: T;
        button2Link?: T;
      };
  aboutSection?:
    | T
    | {
        title?: T;
        aboutCards?:
          | T
          | {
              text?: T;
              image?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        title?: T;
        number?: T;
        serviceCards?:
          | T
          | {
              variant?: T;
              title?: T;
              subtitle?: T;
              content?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              firstButtonText?: T;
              firstButtonLink?: T;
              secondButtonText?: T;
              secondButtonLink?: T;
              id?: T;
            };
      };
  sections?:
    | T
    | {
        sectionType?: T;
        title?: T;
        subtitle?: T;
        images?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        testimonials?:
          | T
          | {
              author?: T;
              text?: T;
              rating?: T;
              avatar?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        telegram?: T;
        instagram?: T;
      };
  additionalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}