/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    footer: Footer;
    header: Header;
    'season-details': SeasonDetail;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    'season-details': SeasonDetailsSelect<false> | SeasonDetailsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  /**
   * Заголовок статті
   */
  title: string;
  /**
   * URL-адреса статті (наприклад: my-article)
   */
  slug: string;
  /**
   * Автор статті
   */
  author: string | User;
  /**
   * Дата публікації
   */
  publishedAt?: string | null;
  /**
   * Статус статті
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Головне зображення статті
   */
  featuredImage?: (string | null) | Media;
  /**
   * Короткий опис статті (для превью)
   */
  excerpt?: string | null;
  /**
   * Основний контент статті
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Категорії статті
   */
  categories?: (string | BlogCategory)[] | null;
  /**
   * Теги для статті
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO заголовок (якщо відрізняється від основного)
   */
  metaTitle?: string | null;
  /**
   * SEO опис
   */
  metaDescription?: string | null;
  /**
   * Час читання в хвилинах (заповнюється автоматично або вручну)
   */
  readTime?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: string;
  /**
   * Назва категорії
   */
  name: string;
  /**
   * URL-адреса категорії
   */
  slug: string;
  /**
   * Опис категорії
   */
  description?: string | null;
  /**
   * Колір категорії (hex код, наприклад: #ff0000)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  /**
   * Ім'я користувача
   */
  name: string;
  /**
   * Email адреса
   */
  email: string;
  /**
   * Номер телефону
   */
  phone: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishedAt?: T;
  status?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  readTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Налаштування домашньої сторінки та її секцій
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  /**
   * Заголовок сторінки
   */
  title: string;
  /**
   * Мета-опис для SEO
   */
  metaDescription?: string | null;
  /**
   * Налаштування головної секції
   */
  heroSection: {
    /**
     * Заголовок hero секції
     */
    title: string;
    /**
     * Колір заголовка у форматі HEX (наприклад: #FF5733 або #000000)
     */
    titleColor?: string | null;
    /**
     * Підзаголовок hero секції
     */
    subtitle?: string | null;
    /**
     * Текст першої кнопки
     */
    buttonText?: string | null;
    /**
     * Посилання на сторінку (наприклад: /blog, /about) або зовнішнє посилання (https://example.com). Якщо вказано, матиме пріоритет над якірем.
     */
    buttonLink?: string | null;
    /**
     * Виберіть ID секції для якоря. Використовується, якщо не вказано посилання.
     */
    buttonAnchor?:
      | ('hero' | 'about' | 'services' | 'advantages' | 'information-camp' | 'about-mentor' | 'guests' | 'footer')
      | null;
    /**
     * Текст другої кнопки (відкриває форму зв'язку)
     */
    button2Text?: string | null;
  };
  /**
   * Налаштування секції 'Про нас'
   */
  aboutSection: {
    /**
     * Заголовок секції 'Про нас'
     */
    title: string;
    /**
     * Колір заголовка у форматі HEX (наприклад: #FF5733 або #000000)
     */
    titleColor?: string | null;
    /**
     * Додайте до 4 карточок для секції 'Про нас'
     */
    aboutCards?:
      | {
          /**
           * Текст карточки
           */
          text: string;
          /**
           * Зображення для карточки
           */
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Налаштування секції 'Послуги'
   */
  servicesSection: {
    /**
     * Заголовок секції 'Послуги'
     */
    title: string;
    /**
     * Колір заголовка у форматі HEX (наприклад: #FF5733 або #000000)
     */
    titleColor?: string | null;
    /**
     * Число для відображення (наприклад, '4')
     */
    number?: string | null;
    /**
     * Додайте до 4 карточок для секції 'Послуги'
     */
    serviceCards?:
      | {
          /**
           * Варіант кольору карточки
           */
          variant: 'green' | 'yellow' | 'orange' | 'blue';
          /**
           * Назва табору (наприклад, 'Next Camp')
           */
          title: string;
          /**
           * Підзаголовок (наприклад, 'Весна')
           */
          subtitle?: string | null;
          /**
           * Додайте пункти списку для карточки
           */
          content?:
            | {
                /**
                 * Текст пункту списку
                 */
                item: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Текст першої кнопки
           */
          firstButtonText?: string | null;
          /**
           * Посилання першої кнопки
           */
          firstButtonLink?: string | null;
          /**
           * Текст другої кнопки (відкриває форму зв'язку)
           */
          secondButtonText?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Налаштування секції 'WOW-фішки'
   */
  advantagesSection: {
    /**
     * Заголовок секції 'WOW-фішки'
     */
    title: string;
    /**
     * Колір заголовка у форматі HEX (наприклад: #FF5733 або #000000)
     */
    titleColor?: string | null;
    /**
     * Зображення для секції (десктопна версія, показується на lg і більше)
     */
    image: string | Media;
    /**
     * Мобільна версія зображення (показується на екранах менше lg)
     */
    mobileImage?: (string | null) | Media;
  };
  /**
   * Налаштування секції 'Next SPORTS + SKILLS'
   */
  informationCampSection: {
    /**
     * Заголовок секції
     */
    title: string;
    /**
     * Колір заголовка у форматі HEX (наприклад: #FF5733 або #000000)
     */
    titleColor?: string | null;
    /**
     * Опис секції
     */
    description?: string | null;
    /**
     * Підзаголовок секції
     */
    subtitle?: string | null;
    sportsCard: {
      /**
       * Заголовок карточки (наприклад, 'NEXT SPORTS' або 'SPORTS')
       */
      title: string;
      /**
       * Додайте спортивні активності
       */
      items?:
        | {
            /**
             * Назва активності
             */
            item: string;
            id?: string | null;
          }[]
        | null;
    };
    skillsCard: {
      /**
       * Заголовок карточки (наприклад, 'NEXT SKILLS')
       */
      title: string;
      /**
       * Додайте навички
       */
      items?:
        | {
            /**
             * Назва навички
             */
            item: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Налаштування секції 'Про ментора'
   */
  aboutMentorSection: {
    /**
     * Заголовок секції (наприклад, 'Хто такий ментор на NEXT CAMP?')
     */
    title: string;
    /**
     * Колір заголовка у форматі HEX (наприклад: #FF5733 або #000000)
     */
    titleColor?: string | null;
    /**
     * Виділена частина заголовка (наприклад, 'ментор')
     */
    titleHighlight?: string | null;
    /**
     * Основний текст опису ментора
     */
    description: string;
    /**
     * Слова/вирази для виділення в описі (через кому, наприклад: 'Це твоя людина в таборі, він надихає, універсальний друг-наставник')
     */
    descriptionHighlights?: string | null;
    /**
     * Виділений текст внизу секції
     */
    highlightText?: string | null;
    /**
     * Слова/вирази для виділення в виділеному тексті (через кому, наприклад: 'NEXT CAMP = спорт + навички + ментори, що підтримують, Вони вчаться бути собою')
     */
    highlightTextHighlights?: string | null;
    /**
     * Зображення для секції
     */
    image?: (string | null) | Media;
  };
  /**
   * Налаштування секції 'Зіркові гості'
   */
  guestsSection: {
    /**
     * Заголовок секції (наприклад, 'Зіркові гості на кожній зміні')
     */
    title: string;
    /**
     * Колір заголовка у форматі HEX (наприклад: #FF5733 або #000000)
     */
    titleColor?: string | null;
    /**
     * Додайте гостей для секції
     */
    guests?:
      | {
          /**
           * Ім'я гостя
           */
          name: string;
          /**
           * Роль/професія гостя (наприклад, 'блогер', 'спортсмен')
           */
          role: string;
          /**
           * Фото гостя
           */
          image?: (string | null) | Media;
          /**
           * Посилання на соціальну мережу гостя (відкривається в новій вкладці)
           */
          networkLink?: string | null;
          /**
           * Текст посилання (за замовчуванням 'Network')
           */
          linkText?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Налаштування футера та контактної інформації
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  contactInfo?: {
    /**
     * Перший номер телефону для контактів
     */
    phone?: string | null;
    /**
     * Другий номер телефону (необовʼязково)
     */
    phone2?: string | null;
    /**
     * Email адреса
     */
    email?: string | null;
    /**
     * Telegram username або посилання (наприклад: @username або https://t.me/username)
     */
    telegram?: string | null;
    /**
     * Instagram username або посилання (наприклад: @username або https://instagram.com/username)
     */
    instagram?: string | null;
  };
  additionalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Налаштування хедера та навігаційного меню
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Перший номер для мобільного меню
   */
  phone?: string | null;
  /**
   * Другий номер для мобільного меню (необовʼязково)
   */
  phone2?: string | null;
  /**
   * Додайте пункти меню. Якщо вказано посилання (url), воно матиме пріоритет. Якщо url відсутнє, використовується якір (anchor). Посилання може бути як внутрішнім (/blog, /about), так і зовнішнім (https://example.com).
   */
  menu?:
    | {
        /**
         * Текст, який відображається в меню
         */
        label: string;
        /**
         * Посилання на сторінку (наприклад: /blog, /about) або зовнішнє посилання (https://example.com). Якщо вказано, матиме пріоритет над якірем.
         */
        url?: string | null;
        /**
         * Виберіть ID секції для якоря. Використовується, якщо не вказано посилання.
         */
        anchor?:
          | ('hero' | 'about' | 'services' | 'advantages' | 'information-camp' | 'about-mentor' | 'guests' | 'footer')
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Редагування деталей для всіх сезонів табору
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season-details".
 */
export interface SeasonDetail {
  id: string;
  /**
   * Дані, які використовуються для всіх сезонів
   */
  common?: {
    buttons?: {
      /**
       * Текст кнопки 'Про табір'
       */
      aboutButtonText?: string | null;
      /**
       * Текст кнопки 'Програма табору'
       */
      programButtonText?: string | null;
      /**
       * Завантажте PDF файл програми табору. Він відкриється в новій вкладці при натисканні на кнопку 'Програма табору'
       */
      programButtonPdf?: (string | null) | Media;
      /**
       * Текст кнопки реєстрації
       */
      registerButtonText?: string | null;
    };
    packages?: {
      silverPackage?: {
        /**
         * Назва пакету
         */
        title?: string | null;
        /**
         * Текст кнопки
         */
        buttonText?: string | null;
      };
      goldPackage?: {
        /**
         * Назва пакету
         */
        title?: string | null;
        /**
         * Текст кнопки
         */
        buttonText?: string | null;
      };
    };
    content?: {
      /**
       * Заголовок умов бронювання
       */
      bookingConditionsTitle?: string | null;
      /**
       * Додайте параграфи для умов бронювання
       */
      bookingConditionsParagraphs?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Заголовок додаткових послуг
       */
      additionalServicesTitle?: string | null;
      additionalServices?:
        | {
            /**
             * Назва послуги
             */
            serviceName: string;
            /**
             * Ціна послуги (необов'язкове поле)
             */
            servicePrice?: number | null;
            id?: string | null;
          }[]
        | null;
      /**
       * Заголовок контактів
       */
      contactTitle?: string | null;
      managers?:
        | {
            /**
             * Ім'я менеджера
             */
            name?: string | null;
            /**
             * Телефон менеджера
             */
            phone?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Унікальні дані для весняного сезону
   */
  весна?: {
    /**
     * Діапазон дат (наприклад: 14.03 — 21.03)
     */
    dateRange?: string | null;
    announcements?: {
      /**
       * Завантажте одне або кілька фото для анонсу (буде показано у слайдері)
       */
      photoAnnouncement?:
        | {
            /**
             * Фото анонс
             */
            photo: string | Media;
            id?: string | null;
          }[]
        | null;
      /**
       * Відео анонс (завантажене відео)
       */
      videoAnnouncement?: (string | null) | Media;
      /**
       * Посилання на YouTube відео (для Shorts або звичайних відео). Приклад: https://www.youtube.com/watch?v=VIDEO_ID або https://youtu.be/VIDEO_ID
       */
      youtubeVideoUrl?: string | null;
    };
    packages?: {
      silverPackage?: {
        /**
         * Ціна пакету
         */
        price?: number | null;
        features?:
          | {
              feature: string;
              /**
               * Відмітьте, щоб зробити текст жирним
               */
              isBold?: boolean | null;
              id?: string | null;
            }[]
          | null;
      };
      goldPackage?: {
        /**
         * Ціна пакету
         */
        price?: number | null;
        features?:
          | {
              feature: string;
              /**
               * Відмітьте, щоб зробити текст жирним
               */
              isBold?: boolean | null;
              id?: string | null;
            }[]
          | null;
      };
    };
  };
  /**
   * Унікальні дані для літнього сезону
   */
  літо?: {
    /**
     * Діапазон дат (наприклад: 14.03 — 21.03)
     */
    dateRange?: string | null;
    announcements?: {
      /**
       * Завантажте одне або кілька фото для анонсу (буде показано у слайдері)
       */
      photoAnnouncement?:
        | {
            /**
             * Фото анонс
             */
            photo: string | Media;
            id?: string | null;
          }[]
        | null;
      /**
       * Відео анонс (завантажене відео)
       */
      videoAnnouncement?: (string | null) | Media;
      /**
       * Посилання на YouTube відео (для Shorts або звичайних відео). Приклад: https://www.youtube.com/watch?v=VIDEO_ID або https://youtu.be/VIDEO_ID
       */
      youtubeVideoUrl?: string | null;
    };
    packages?: {
      silverPackage?: {
        /**
         * Ціна пакету
         */
        price?: number | null;
        features?:
          | {
              feature: string;
              /**
               * Відмітьте, щоб зробити текст жирним
               */
              isBold?: boolean | null;
              id?: string | null;
            }[]
          | null;
      };
      goldPackage?: {
        /**
         * Ціна пакету
         */
        price?: number | null;
        features?:
          | {
              feature: string;
              /**
               * Відмітьте, щоб зробити текст жирним
               */
              isBold?: boolean | null;
              id?: string | null;
            }[]
          | null;
      };
    };
  };
  /**
   * Унікальні дані для осіннього сезону
   */
  осінь?: {
    /**
     * Діапазон дат (наприклад: 14.03 — 21.03)
     */
    dateRange?: string | null;
    announcements?: {
      /**
       * Завантажте одне або кілька фото для анонсу (буде показано у слайдері)
       */
      photoAnnouncement?:
        | {
            /**
             * Фото анонс
             */
            photo: string | Media;
            id?: string | null;
          }[]
        | null;
      /**
       * Відео анонс (завантажене відео)
       */
      videoAnnouncement?: (string | null) | Media;
      /**
       * Посилання на YouTube відео (для Shorts або звичайних відео). Приклад: https://www.youtube.com/watch?v=VIDEO_ID або https://youtu.be/VIDEO_ID
       */
      youtubeVideoUrl?: string | null;
    };
    packages?: {
      silverPackage?: {
        /**
         * Ціна пакету
         */
        price?: number | null;
        features?:
          | {
              feature: string;
              /**
               * Відмітьте, щоб зробити текст жирним
               */
              isBold?: boolean | null;
              id?: string | null;
            }[]
          | null;
      };
      goldPackage?: {
        /**
         * Ціна пакету
         */
        price?: number | null;
        features?:
          | {
              feature: string;
              /**
               * Відмітьте, щоб зробити текст жирним
               */
              isBold?: boolean | null;
              id?: string | null;
            }[]
          | null;
      };
    };
  };
  /**
   * Унікальні дані для зимового сезону
   */
  зима?: {
    /**
     * Діапазон дат (наприклад: 14.03 — 21.03)
     */
    dateRange?: string | null;
    announcements?: {
      /**
       * Завантажте одне або кілька фото для анонсу (буде показано у слайдері)
       */
      photoAnnouncement?:
        | {
            /**
             * Фото анонс
             */
            photo: string | Media;
            id?: string | null;
          }[]
        | null;
      /**
       * Відео анонс (завантажене відео)
       */
      videoAnnouncement?: (string | null) | Media;
      /**
       * Посилання на YouTube відео (для Shorts або звичайних відео). Приклад: https://www.youtube.com/watch?v=VIDEO_ID або https://youtu.be/VIDEO_ID
       */
      youtubeVideoUrl?: string | null;
    };
    packages?: {
      silverPackage?: {
        /**
         * Ціна пакету
         */
        price?: number | null;
        features?:
          | {
              feature: string;
              /**
               * Відмітьте, щоб зробити текст жирним
               */
              isBold?: boolean | null;
              id?: string | null;
            }[]
          | null;
      };
      goldPackage?: {
        /**
         * Ціна пакету
         */
        price?: number | null;
        features?:
          | {
              feature: string;
              /**
               * Відмітьте, щоб зробити текст жирним
               */
              isBold?: boolean | null;
              id?: string | null;
            }[]
          | null;
      };
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  title?: T;
  metaDescription?: T;
  heroSection?:
    | T
    | {
        title?: T;
        titleColor?: T;
        subtitle?: T;
        buttonText?: T;
        buttonLink?: T;
        buttonAnchor?: T;
        button2Text?: T;
      };
  aboutSection?:
    | T
    | {
        title?: T;
        titleColor?: T;
        aboutCards?:
          | T
          | {
              text?: T;
              image?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        title?: T;
        titleColor?: T;
        number?: T;
        serviceCards?:
          | T
          | {
              variant?: T;
              title?: T;
              subtitle?: T;
              content?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              firstButtonText?: T;
              firstButtonLink?: T;
              secondButtonText?: T;
              id?: T;
            };
      };
  advantagesSection?:
    | T
    | {
        title?: T;
        titleColor?: T;
        image?: T;
        mobileImage?: T;
      };
  informationCampSection?:
    | T
    | {
        title?: T;
        titleColor?: T;
        description?: T;
        subtitle?: T;
        sportsCard?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
            };
        skillsCard?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
            };
      };
  aboutMentorSection?:
    | T
    | {
        title?: T;
        titleColor?: T;
        titleHighlight?: T;
        description?: T;
        descriptionHighlights?: T;
        highlightText?: T;
        highlightTextHighlights?: T;
        image?: T;
      };
  guestsSection?:
    | T
    | {
        title?: T;
        titleColor?: T;
        guests?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              networkLink?: T;
              linkText?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contactInfo?:
    | T
    | {
        phone?: T;
        phone2?: T;
        email?: T;
        telegram?: T;
        instagram?: T;
      };
  additionalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  phone?: T;
  phone2?: T;
  menu?:
    | T
    | {
        label?: T;
        url?: T;
        anchor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season-details_select".
 */
export interface SeasonDetailsSelect<T extends boolean = true> {
  common?:
    | T
    | {
        buttons?:
          | T
          | {
              aboutButtonText?: T;
              programButtonText?: T;
              programButtonPdf?: T;
              registerButtonText?: T;
            };
        packages?:
          | T
          | {
              silverPackage?:
                | T
                | {
                    title?: T;
                    buttonText?: T;
                  };
              goldPackage?:
                | T
                | {
                    title?: T;
                    buttonText?: T;
                  };
            };
        content?:
          | T
          | {
              bookingConditionsTitle?: T;
              bookingConditionsParagraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              additionalServicesTitle?: T;
              additionalServices?:
                | T
                | {
                    serviceName?: T;
                    servicePrice?: T;
                    id?: T;
                  };
              contactTitle?: T;
              managers?:
                | T
                | {
                    name?: T;
                    phone?: T;
                    id?: T;
                  };
            };
      };
  весна?:
    | T
    | {
        dateRange?: T;
        announcements?:
          | T
          | {
              photoAnnouncement?:
                | T
                | {
                    photo?: T;
                    id?: T;
                  };
              videoAnnouncement?: T;
              youtubeVideoUrl?: T;
            };
        packages?:
          | T
          | {
              silverPackage?:
                | T
                | {
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          isBold?: T;
                          id?: T;
                        };
                  };
              goldPackage?:
                | T
                | {
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          isBold?: T;
                          id?: T;
                        };
                  };
            };
      };
  літо?:
    | T
    | {
        dateRange?: T;
        announcements?:
          | T
          | {
              photoAnnouncement?:
                | T
                | {
                    photo?: T;
                    id?: T;
                  };
              videoAnnouncement?: T;
              youtubeVideoUrl?: T;
            };
        packages?:
          | T
          | {
              silverPackage?:
                | T
                | {
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          isBold?: T;
                          id?: T;
                        };
                  };
              goldPackage?:
                | T
                | {
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          isBold?: T;
                          id?: T;
                        };
                  };
            };
      };
  осінь?:
    | T
    | {
        dateRange?: T;
        announcements?:
          | T
          | {
              photoAnnouncement?:
                | T
                | {
                    photo?: T;
                    id?: T;
                  };
              videoAnnouncement?: T;
              youtubeVideoUrl?: T;
            };
        packages?:
          | T
          | {
              silverPackage?:
                | T
                | {
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          isBold?: T;
                          id?: T;
                        };
                  };
              goldPackage?:
                | T
                | {
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          isBold?: T;
                          id?: T;
                        };
                  };
            };
      };
  зима?:
    | T
    | {
        dateRange?: T;
        announcements?:
          | T
          | {
              photoAnnouncement?:
                | T
                | {
                    photo?: T;
                    id?: T;
                  };
              videoAnnouncement?: T;
              youtubeVideoUrl?: T;
            };
        packages?:
          | T
          | {
              silverPackage?:
                | T
                | {
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          isBold?: T;
                          id?: T;
                        };
                  };
              goldPackage?:
                | T
                | {
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          isBold?: T;
                          id?: T;
                        };
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}